title:             2e18 - Tech Blog
email:            joe@2e18.com
description:       A Blog about Tech
author:            Joe Sprankle
baseurl:           ""
url:               "http://www.2e18.com"

# Social Profiles
twitter_username:  joe_sprankle
github_username:   joesprankle
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
